[package]
name = "fluorine"
description = "placeholder"
version = "0.1.0"
authors = ["Miles Rout <miles.rout@gmail.com>"]
repository = "https://github.com/milesrout/fluorine"
license = "MIT"
homepage = "https://miles.rout.co.nz/fluorine"

[dependencies]
